# Generated by Django 5.0.3 on 2024-07-31 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='estimated_time',
            new_name='estimated_hours',
        ),
    ]
