# Generated by Django 5.0.3 on 2024-08-02 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0003_remove_asset_active_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
