# Generated by Django 5.0.3 on 2024-08-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0004_alter_workorder_status_alter_workorderrecord_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='due_date',
            new_name='first_due_date',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='completed_on',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='estimated_hours',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='planned_start_date',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='started_on',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='time_to_complete',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='work_type',
        ),
        migrations.AlterField(
            model_name='workorderrecord',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('done', 'Done'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
