# Generated by Django 5.0.3 on 2024-08-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0004_alter_asset_code_alter_workorder_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='recurrence',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='once', max_length=20),
        ),
    ]
