# Generated by Django 5.0.3 on 2024-08-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0006_kpi_kpivalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, choices=[('warehouse', 'Warehouse'), ('production', 'Production')], max_length=20, null=True),
        ),
    ]
