# Generated by Django 5.0.3 on 2024-08-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0007_alter_asset_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, choices=[('warehouse', 'Warehouse'), ('office', 'Office'), ('quality', 'Quality'), ('compounding', 'Compounding'), ('bulding', 'Building'), ('production Line #1', 'Production Line #1'), ('production Line #2', 'Production Line #2'), ('production Line #3', 'Production Line #3'), ('assembly', 'Assembly')], max_length=20, null=True),
        ),
    ]
