# Generated by Django 5.0.3 on 2024-10-08 18:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cap',
            field=models.CharField(choices=[('Flip Top', 'Flip Top'), ('Disc Cap', 'Disc Cap'), ('Pump', 'Pump'), ('Screw Cap', 'Screw Cap'), ('Spray', 'Spray'), ('Twist Cap', 'Twist Cap'), ('None', 'None'), ('N/A', 'N/A')], default='Flip Top', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='privatelabel.customer'),
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('Customer Supplied', 'Customer Supplied'), ('Custom Label', 'Custom Label'), ('None', 'None')], default='Customer Supplied', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='lube',
            field=models.CharField(choices=[('Glide', 'Glide'), ('Silk', 'Silk'), ('Millennium', 'Millennium'), ('Free', 'Free')], default='Glide', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='package',
            field=models.CharField(choices=[('Bottle', 'Bottle'), ('Tube', 'Tube'), ('Pump', 'Pump'), ('Jar', 'Jar'), ('Sachet', 'Sachet')], default='Bottle', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('12 ml', '12 ml'), ('1 oz', '1 oz'), ('2.2 oz', '2.2 oz'), ('4.4 oz', '4.4 oz'), ('8 oz', '8 oz'), ('16 oz', '16 oz'), ('32 oz', '32 oz'), ('64 oz', '64 oz'), ('128 oz', '128 oz')], default='12 ml', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='spec_version',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=200)),
                ('po_qty', models.IntegerField()),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('desired_date', models.DateField()),
                ('expected_ship_date', models.DateField()),
                ('week_scheduled', models.IntegerField()),
                ('deposit_stat', models.BooleanField(default=False)),
                ('ingredients_stat', models.BooleanField(default=False)),
                ('spec_stat', models.BooleanField(default=False)),
                ('package_stat', models.BooleanField(default=False)),
                ('cap_stat', models.BooleanField(default=False)),
                ('label_stat', models.BooleanField(default=False)),
                ('box_stat', models.BooleanField(default=False)),
                ('last_component_eta', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('released_to_warehouse', models.BooleanField(default=False)),
                ('shipped', models.BooleanField(default=False)),
                ('coordinator_notes', models.TextField()),
                ('planning_notes', models.TextField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='privatelabel.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='privatelabel.product')),
            ],
        ),
    ]
