# Generated by Django 5.0.3 on 2024-10-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0003_alter_order_coordinator_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='box_stat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cap_stat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coordinator_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='deposit_stat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ingredients_stat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='label_stat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_component_eta',
        ),
        migrations.RemoveField(
            model_name='order',
            name='package_stat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='planning_notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='released_to_warehouse',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped',
        ),
        migrations.RemoveField(
            model_name='order',
            name='spec_stat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='week_scheduled',
        ),
    ]
