# Generated by Django 5.0.3 on 2024-10-08 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0004_remove_order_box_stat_remove_order_cap_stat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_entered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='desired_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expected_ship_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='po_qty',
        ),
    ]
