# Generated by Django 5.0.3 on 2024-10-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0005_remove_order_date_entered_remove_order_date_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_entered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='po_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
