# Generated by Django 5.0.3 on 2024-10-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0006_order_date_entered_order_date_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='box_stat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='cap_stat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='coordinator_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_stat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='desired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_ship_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ingredients_stat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='label_stat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='last_component_eta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='package_stat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='planning_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='released_to_warehouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='spec_stat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
