# Generated by Django 5.0.3 on 2024-10-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0008_order_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='updated',
            new_name='last_updated',
        ),
    ]
