# Generated by Django 5.0.3 on 2024-10-09 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0009_rename_updated_order_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
