# Generated by Django 5.0.3 on 2024-10-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0011_alter_product_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='po_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='po_qty',
            new_name='qty',
        ),
    ]
