# Generated by Django 5.0.3 on 2024-10-12 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0012_rename_po_number_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
