# Generated by Django 5.0.3 on 2024-10-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0014_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
