# Generated by Django 5.0.3 on 2024-10-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0015_rename_notes_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='content',
        ),
    ]
