# Generated by Django 5.0.3 on 2024-11-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0022_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='qty',
            field=models.FloatField(),
        ),
    ]
