# Generated by Django 5.0.3 on 2025-01-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0024_order_customerid_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='salesperson',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
