# Generated by Django 5.0.3 on 2025-01-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0025_order_salesperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
