# Generated by Django 5.0.3 on 2025-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0027_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
