# Generated by Django 5.0.3 on 2025-01-31 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0029_alter_order_coordinator_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='released_to_warehouse',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipped',
        ),
    ]
