# Generated by Django 5.0.3 on 2025-01-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0030_remove_order_released_to_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uom',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
