# Generated by Django 5.0.3 on 2025-02-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privatelabel', '0031_order_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_notes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
