# Generated by Django 4.1.7 on 2024-02-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthdate',
            new_name='birthday',
        ),
    ]
