# Generated by Django 5.0.3 on 2024-04-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_training_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='training_events',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
