# Generated by Django 4.1.7 on 2024-03-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='users.role'),
        ),
    ]
