# Generated by Django 5.0.3 on 2024-04-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_training_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='training_events',
            field=models.TextField(blank=True, default=''),
        ),
    ]
