# Generated by Django 5.0.3 on 2024-04-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_training_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='training_modules_row',
            field=models.TextField(blank=True, default=''),
        ),
    ]
