# Generated by Django 5.0.3 on 2024-04-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_role_training_modules_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='training_modules_row',
        ),
        migrations.CreateModel(
            name='RoleTrainingModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.TextField(blank=True, default='')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
            ],
        ),
    ]
