# Generated by Django 5.0.3 on 2024-04-26 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profiletrainingevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletrainingevents',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='roletrainingmodules',
            name='role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
