# Generated by Django 5.0.3 on 2024-04-26 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profiletrainingevents_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileTrainingEvents',
        ),
    ]
