# Generated by Django 4.1.7 on 2024-03-14 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CertificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=50)),
                ('scheduled_date', models.DateField(blank=True, default=datetime.datetime(2024, 3, 29, 18, 25, 25, 148403, tzinfo=datetime.timezone.utc), null=True)),
                ('due_date', models.DateField(blank=True, default=datetime.datetime(2024, 3, 29, 18, 25, 25, 148860, tzinfo=datetime.timezone.utc), null=True)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.certification')),
            ],
        ),
    ]
