# Generated by Django 5.0.3 on 2024-04-01 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingevent',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='TrainingModules', to='users.role'),
        ),
        migrations.AddField(
            model_name='trainingevent',
            name='training_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingmodule'),
        ),
    ]
