# Generated by Django 4.1.7 on 2024-02-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issuing_organization',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='users',
        ),
    ]
