# Generated by Django 5.0.3 on 2024-04-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmodule',
            name='roles',
        ),
    ]
