# Generated by Django 4.1.7 on 2024-02-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificationstatus',
            old_name='completion_status',
            new_name='status',
        ),
    ]
