# Generated by Django 5.0.3 on 2024-04-26 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_trainingmodule_roles'),
        ('users', '0010_delete_profiletrainingevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileTrainingEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.TextField(blank=True, default='')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
