# Generated by Django 4.1.7 on 2024-03-21 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_remove_certificationstatus_scheduled_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationstatus',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='certificationstatus',
            name='completed_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 5, 1, 23, 48, 216076, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
