# Generated by Django 4.1.7 on 2024-02-24 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_certification_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='department',
            new_name='departments',
        ),
        migrations.AlterField(
            model_name='certificationstatus',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 10, 2, 14, 5, 696708, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='certificationstatus',
            name='scheduled_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 10, 2, 14, 5, 696203, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
