# Generated by Django 4.1.7 on 2024-03-21 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_remove_certificationstatus_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='exp_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationstatus',
            name='completed_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 5, 1, 31, 47, 86933, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
