# Generated by Django 4.1.7 on 2024-02-24 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_rename_department_certification_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationstatus',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 10, 18, 54, 24, 51387, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='certificationstatus',
            name='scheduled_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 10, 18, 54, 24, 50908, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
