# Generated by Django 5.0.3 on 2024-04-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_profiletrainingevents_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletrainingevents',
            name='row',
            field=models.TextField(blank=True, default=''),
        ),
    ]
