# Generated by Django 5.0.3 on 2024-03-24 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_rename_schedule_date_certification_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificationstatus',
            name='completed_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 8, 22, 22, 0, 691464, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='certificationstatus',
            name='status',
            field=models.CharField(choices=[('To be Scheduled', 'To be Scheduled'), ('Scheduled', 'Scheduled'), ('Expired', 'Expired'), ('About To Expired', 'About To Expired'), ('Completed', 'Completed')], default='To be Scheduled', max_length=50),
        ),
    ]
