# Generated by Django 5.0.3 on 2024-07-18 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_kpi_kpivalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmodule',
            name='scheduled_date',
        ),
    ]
