# Generated by Django 5.0.3 on 2024-03-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_alter_certification_scheduled_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationstatus',
            name='status',
        ),
        migrations.AlterField(
            model_name='certificationstatus',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
