# Generated by Django 5.0.3 on 2024-03-28 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_remove_certificationstatus_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificationstatus',
            options={'ordering': ['completed_date']},
        ),
    ]
