# Generated by Django 5.0.3 on 2024-07-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_remove_trainingmodule_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodule',
            name='other',
            field=models.BooleanField(default=False),
        ),
    ]
