# Generated by Django 5.0.3 on 2024-03-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_alter_certificationstatus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificationstatus',
            options={'ordering': ['-completed_date']},
        ),
    ]
