# Generated by Django 5.0.3 on 2024-03-28 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_alter_certificationstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationstatus',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificationstatus',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
