# Generated by Django 4.1.7 on 2024-03-08 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_alter_certificationstatus_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='departments',
        ),
        migrations.AlterField(
            model_name='certificationstatus',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 23, 19, 7, 52, 103261, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='certificationstatus',
            name='scheduled_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 23, 19, 7, 52, 101904, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
