# Generated by Django 4.1.7 on 2024-03-08 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_remove_certification_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationstatus',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 23, 19, 9, 43, 305539, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='certificationstatus',
            name='scheduled_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 23, 19, 9, 43, 305107, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
