# Generated by Django 4.1.7 on 2024-03-08 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_roles'),
        ('training', '0017_certification_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='role',
        ),
        migrations.AlterField(
            model_name='certificationstatus',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 23, 19, 32, 49, 76171, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='certificationstatus',
            name='scheduled_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 3, 23, 19, 32, 49, 75737, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='certifications', to='users.role'),
        ),
    ]
